plugin: aws_ec2
regions:
  - us-east-1
filters:
  tag:Name:
    - benchmark_server
compose:
  ansible_host: public_ip_address
  ansible_user: "'ubuntu'"
keyed_groups:
  - key: tags.Name
    prefix: ""
    separator: ""
