- name: Install NTL from source
  hosts: benchmark_server
  vars:
    source_url: "https://libntl.org/ntl-11.5.1.tar.gz"
    source_checksum: "sha256:210d06c31306cbc6eaf6814453c56c776d9d8e8df36d74eb306f6a523d1c6a8a"
    build_dir: "/home/ubuntu/build-ntl/"
    extracted_dir: "ntl-11.5.1/src/"
  tasks:
    - name: Create build directory
      file:
        path: "{{ build_dir }}"
        state: directory
        mode: '0755'
    - name: Download source code
      get_url:
        url: "{{ source_url }}"
        dest: "{{ build_dir }}/src.tar.gz"
        checksum: "{{ source_checksum }}"
        mode: '0644'
      register: download_result
    
    - name: Extract archive
      unarchive:
        src: "{{ build_dir }}/src.tar.gz"
        dest: "{{ build_dir }}"
        remote_src: yes
        creates: "{{ build_dir }}/{{ extracted_dir }}"
      when: download_result.changed

    - name: Run configure script
      command:
        cmd: ./configure NTL_GMP_LIP=on
        chdir: "{{ build_dir }}/{{ extracted_dir }}"
      args:
        creates: "{{ build_dir }}/{{ extracted_dir }}/Makefile"
      register: configure_result

    - name: Run make
      command:
        cmd: make
        chdir: "{{ build_dir }}/{{ extracted_dir }}"
      register: make_result
      when: configure_result.changed

    - name: Run make install
      command:
        cmd: make install
        chdir: "{{ build_dir }}/{{ extracted_dir }}"
      when: make_result.changed
      become: yes
