- name: Setup Benchmark Protocol
  hosts: benchmark_server
  vars:
    repo_dir: "/home/ubuntu/secure-aggregation-monorepo"
    build_dir: "{{ repo_dir }}/protocol/build"
  tasks:
    - name: Copy over ssh deploy private key
      ansible.builtin.copy:
        src: ./id_ed25519
        dest: ~/.ssh/id_ed25519
        owner: ubuntu
        group: ubuntu
        mode: "0600"
    - name: Copy over ssh deploy public key
      ansible.builtin.copy:
        src: ./id_ed25519.pub
        dest: ~/.ssh/id_ed25519.pub
        owner: ubuntu
        group: ubuntu
        mode: "0644"

    - name: Pull repo
      git:
        repo: git@github.com:heldridge/secure-aggregation-monorepo.git
        dest: "{{ repo_dir }}"
        accept_hostkey: yes

    - name: Create build directory
      file:
        path: "{{ build_dir }}"
        state: directory
        mode: "0755"

    - name: Run CMake
      command:
        chdir: "{{ build_dir }}"
        cmd: "cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DCMAKE_BUILD_TYPE=Release .."
        creates: "{{ build_dir }}/Makefile"
      register: cmake_result

    - name: Run make
      command:
        chdir: "{{ build_dir }}"
        cmd: "make -j"
      register: make_result
      when: cmake_result.changed

